version: "2"
services:
  cloud-manager:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - VULTR_KEY=${VULTR_KEY}
        - DIGITALOCEAN_TOKEN=${DIGITALOCEAN_TOKEN}
        - USE_MIRROR=${USE_MIRROR}
    networks:
      - cloud-manager
  salt:
    build:
      context: ./salt
      dockerfile: Dockerfile
      args:
        - VULTR_KEY=${VULTR_KEY}
        - DIGITALOCEAN_TOKEN=${DIGITALOCEAN_TOKEN}
        - USE_MIRROR=${USE_MIRROR}
    volumes:
      - ./salt:/app
      - ./salt/etc/salt/master.d:/etc/salt/master.d
    working_dir: /app
    command: salt-api
    expose:
      - 8000
  terraform:
    build:
      context: ./terraform
      dockerfile: Dockerfile
      args:
        - VULTR_KEY=${VULTR_KEY}
        - DIGITALOCEAN_TOKEN=${DIGITALOCEAN_TOKEN}
    working_dir: /app
    volumes: 
      - ./terraform:/app
networks:
  cloud-manager: