version: "3.2"
services:
  cloud-manager:
    build:
      context: .
      dockerfile: docker/cloudmanager/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: cloud-manager
    working_dir: /app
    ports:
      - 8888:5000
    volumes: 
      - ./cloudmanager:/app
      - cloud-manager-share:/cloud-manager-share
      - /var/run/docker.sock:/var/run/docker.sock
      - ./secrets:/var/run/secrets
    privileged: true
    networks:
      - cloud-manager
  terraform:
    build:
      context: .
      dockerfile: docker/terraform/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: cloud-manager-terraform
    volumes: 
      - tf-workspace:/app
      - ./secrets:/var/run/secrets
    environment:
      - TF_VAR_MASTER_COUNT=${TF_VAR_SERVANT_COUNT:-0}
      - TF_VAR_MASTER_PLAN=${TF_VAR_MASTER_PLAN:-starter}
      - TF_VAR_SERVANT_COUNT=${TF_VAR_SERVANT_COUNT:-0}
      - TF_VAR_SERVANT_PLAN=${TF_VAR_SERVANT_PLAN:-starter}
    networks:
      - cloud-manager
  salt:
    build:
      context: .
      dockerfile: docker/salt/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: cloud-manager-salt
    volumes: 
      - cloud-manager-share:/cloud-manager-share
      - ./salt/srv/salt:/srv/salt
      - ./salt/srv/pillar:/srv/pillar
      - ./secrets:/var/run/secrets
    networks:
      - cloud-manager
networks:
  cloud-manager:
volumes:
  tf-workspace:
  cloud-manager-share:
