version: "3.1"
services:
  cloud-manager:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR}
    networks:
      - cloud-manager
    secrets:
      - VULTR_KEY
      - DIGITALOCEAN_TOKEN
  salt:
    build:
      context: ./salt
      dockerfile: Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR}
    volumes:
      - ./salt:/app
      - ./salt/etc/salt/master.d:/etc/salt/master.d
    working_dir: /app
    command: salt-api
    expose:
      - 8000
    secrets:
      - VULTR_KEY
      - DIGITALOCEAN_TOKEN
  terraform:
    build:
      context: ./terraform
      dockerfile: Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR}
    working_dir: /app
    volumes: 
      - ./terraform:/app
    secrets:
      - VULTR_KEY
      - DIGITALOCEAN_TOKEN
networks:
  cloud-manager:
secrets:
  VULTR_KEY:
    file: secrets/vultr.txt
  DIGITALOCEAN_TOKEN:
    file: secrets/digitalocean.txt