version: "3.2"
services:
  cloud-manager:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    networks:
      - cloud-manager
    secrets:
      - VULTR_KEY
      - DIGITALOCEAN_TOKEN
  terraform:
    build:
      context: .
      dockerfile: docker/terraform/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    working_dir: /app
    volumes: 
      - ./docker/terraform:/app
    networks:
      - cloud-manager
    secrets:
      - VULTR_KEY
      - DIGITALOCEAN_TOKEN
    entrypoint: bash -c
networks:
  cloud-manager:
secrets:
  VULTR_KEY:
    file: secrets/vultr.txt
  DIGITALOCEAN_TOKEN:
    file: secrets/digitalocean.txt
